kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: api-dev-rolebinding
  namespace: api-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-dev
subjects:
- kind: User
  namespace: api-dev
  name: api-dev
