---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: api-dev-role
  namespace: api-dev
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: api-dev-rolebinding
  namespace: api-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-dev-role
subjects:
- kind: User
  namespace: api-dev
  name: "apidev@OTAPRD344ops.onmicrosoft.com"
