apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: api-dev
  labels:
    app: poi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registry9cv6941.azurecr.io/tripinsights/poi:cga
        volumeMounts:
          - name: kvsecrets
            mountPath: /secrets
            readOnly: true
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "local"
          name: SQL_SERVER
          value: "sqlserver9cv6941.database.windows.net"
      volumes:
        - name: kvsecrets
          flexVolume:
              driver: "azure/kv"
              secretRef:
                name: clusspncreds                 # [OPTIONAL] not required if using Pod Identity
              options:
                usepodidentity: "false"        # [OPTIONAL] if not provided, will default to "false"
                keyvaultname: "aka010kv"               # the name of the KeyVault
                keyvaultobjectnames: sql_user;sql_passsword    # list of KeyVault object names (semi-colon separated)
                keyvaultobjecttypes: secret;secret  # list of KeyVault object types: secret, key or cert (semi-colon separated)
                keyvaultobjectversions: ""     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
                resourcegroup: "teamResources" # [REQUIRED FOR < v0.0.14] the resource group of the KeyVault
                subscriptionid: "ae235c5e-7998-4b1d-9a67-40dfcab3f663" # [REQUIRED FOR < v0.0.14] the subscription ID of the KeyVault
                tenantid: "9a415ae5-df41-4e4c-b688-ee2ad23711b8" # the tenant ID of the KeyVault  