apiVersion: apps/v1 

kind: Deployment 

metadata: 

  name: trips-deployment 
  namespace: api-dev

  labels: 

    app: trips-deployment 

spec: 

  replicas: 2 

  selector: 

    matchLabels: 

      app: trips 

  template: 

    metadata: 

      labels: 

        app: trips 

    spec: 

      containers: 

      - name: trips 

        image: registry9cv6941.azurecr.io/tripinsights/trips:cgb 

        ports: 

        - containerPort: 80 

        env: 

        - name: ASPNETCORE_ENVIRONMENT 

          value: "local" 

        - name: SQL_USER 

          value: "sqladmin9Cv6941" 

        - name: SQL_PASSWORD 

          value: "pC3kn9T85" 

        - name: SQL_SERVER 

          value: "sqlserver9cv6941.database.windows.net" 