---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: web-dev-role
  namespace: web-dev
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: web-dev-rolebinding
  namespace: web-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-role
subjects:
- kind: User
  namespace: web-dev
  name: "webdev@OTAPRD344ops.onmicrosoft.com"

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: web-dev-read-role
  namespace: web-dev
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: web-dev-read-rolebinding
  namespace: web-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-read-role
subjects:
- kind: User
  namespace: web-dev
  name: "apidev@OTAPRD344ops.onmicrosoft.com"
